on:
  push:
  pull_request:
    branches:
      - main

jobs:
  write-good:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Run write-good linter
        uses: jdlabelle/write-good-action@main
